framework:
    assets:
        packages:
            lokiai:
                json_manifest_path: '%kernel.project_dir%/public/bundles/lokiai/manifest.json'

loki_ai:
    providers:
        openai:
            api_key: '%env(default:loki_ai.empty:OPENAI_API_KEY)%'
            model: gpt-4o-mini
            temperature: 0.5
            max_tokens: 100
        claude:
            api_key: '%env(default:loki_ai.empty:ANTHROPIC_API_KEY)%'
            model: claude-sonnet-4-6
            temperature: 0.5
            max_tokens: 100
